---

- name: Import jenkins repo
  shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install jenkins
  yum:
      name: jenkins
      stat: present

- name: Start jenkins
  service:
      name: jenkins
      stat: 
